try:
    result = 45/0
except:
    print('Error Happend')
finally:
    print('Done')